INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (1, 'Ahorros Largos BBVA', 4, 'COP', '21.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (2, 'Ahorros BBVA', 4, 'COP', '-27897.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (3, 'Billetera', 5, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (4, 'Visa BBVA', 9, 'COP', '-1695729.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (5, 'Rappi Card', 9, 'COP', '1835250.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (6, 'Ahorro Bancolombia', 4, 'COP', '332792.87', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (7, 'Ahorro Falabella', 4, 'COP', '6384.31', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (8, 'Inversiones BBVA', 6, 'COP', '832785.37', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (9, 'Arnold', 2, 'COP', '20000.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (10, 'Felipe', 7, 'COP', '320000.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (11, 'Gerital', 11, 'COP', '-20000.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (12, 'Alcancía De Monedas', 5, 'COP', '45000.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (13, 'Edna', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (14, 'Sebas', 7, 'COP', '20000.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (15, 'Acmin', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (16, 'Daviplata', 15, 'COP', '400.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (17, 'Ahorros Davivienda', 4, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (18, 'Préstamo Davivienda', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (19, 'MasterCard Falabella', 9, 'COP', '0.00', 0, 0, '0.28');
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (20, 'Mastercard Davivienda', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (21, 'Sebas Mono', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (22, 'Monedero', 5, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (23, 'Binance', 15, 'USD', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (24, 'Foody', 15, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (25, 'Mastercard Bogota', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (26, 'Think-e', 3, 'COP', '-6195000.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (27, 'Tyba', 6, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (28, 'Credi Occidente', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (29, 'Mercancía', 2, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (30, 'Coinsenda', 15, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (31, 'Libertex', 15, 'USD', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (32, 'Nequi', 15, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (33, 'Jenny', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (34, 'MasterCard Occidente', 9, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (35, 'Icetex', 10, 'COP', '-980000.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (36, 'Préstamo BBVA', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (37, 'Mami', 7, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (38, 'Karen', 7, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (39, 'Yefer', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (40, 'Paxful', 15, 'USD', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (41, 'PayPal', 15, 'USD', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (42, 'A2censo', 6, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (43, 'Unergy', 6, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (44, 'Sofi', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (45, 'Sergio', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (46, 'Yefer', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (47, 'Wen', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (48, 'David', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (49, 'Stripe', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (50, 'Préstamo BBVA 2', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (51, 'Wise', 15, 'EUR', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (52, 'TC Nu', 9, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (53, 'Kari', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (54, 'Elixir', 6, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (55, 'Leidy', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (56, 'Préstamo BBVA 3', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (57, 'Camilo', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (58, 'People Pass', 4, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (59, 'AvVillas', 4, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (60, 'Ahorros Falabella 2', 4, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (61, 'Préstamo av villas', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (62, 'Mastercard Itaú', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (63, 'Viejo', 7, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (64, 'Visa Itaú', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (65, 'Geral', 7, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (66, 'Leafar', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (67, 'Juancho Trabajador', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (68, 'Alfonso Chima', 11, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (69, 'Juan Cuñado', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (70, 'Movistar Crédito', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (71, 'Tío Carlos', 7, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (72, 'Crédito Fallabela', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (73, 'Ahorros Itaú', 4, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (74, 'Ferreteria', 11, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (75, 'Fabio Avellaneda', 10, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (76, 'Mastercard AvVillas', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (77, 'Visa AvVillas', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (78, 'Ualá', 15, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (79, 'Ahorros Bogotá', 4, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (80, 'crédito Bogotá', 10, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (81, 'Visa Bogotá', 9, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (82, 'Mesfix', 6, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (83, 'PAC Fallabella Casa', 4, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (84, 'Xile', 7, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (85, 'Casa Cisne', 6, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (86, 'PAC Fallabela Remodelación', 4, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (87, 'Visa Occidente', 9, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (88, 'Luz - Acueducto', 7, 'COP', '0.00', 1, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (89, 'Nissan Pathfinder R50', 8, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (90, 'Apartamento Vicinio 1503', 8, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (91, 'Nu', 4, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (92, 'Colfondos Voluntaria ', 6, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (93, 'AFC AV Villas ', 6, 'COP', '5000000.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (94, 'Davivienda ', 4, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (95, 'Bono alimenticio ', 4, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (96, 'Alcancía Billetes ', 5, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (97, 'Hipotecario Bancolombia ', 10, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (98, 'Casa Vicinio ', 8, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (99, 'AFC Davivienda ', 6, 'COP', '0.00', 0, 0, NULL);
INSERT INTO accounts (id, name, type_id, currency_code, opening_balance, is_hidden, applies_gmf, default_interest_rate) VALUES (100, 'AFC BBVA ', 6, 'COP', '0.00', 0, 0, NULL);
