INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (1, 'Otros', NULL, 'EXPENSE', NULL, 1);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (2, 'Otros', NULL, 'INCOME', NULL, 2);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (3, '(Sin Categoría)', NULL, 'INCOME', NULL, 3);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (4, '(Sin Categoría)', NULL, 'EXPENSE', NULL, 4);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (5, 'Entretenimiento', NULL, 'EXPENSE', NULL, 5);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (6, 'Casa', NULL, 'EXPENSE', NULL, 6);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (7, 'Utilidades', NULL, 'EXPENSE', NULL, 7);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (8, 'Empleador', NULL, 'INCOME', NULL, 8);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (9, 'Negocios', NULL, 'INCOME', NULL, 9);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (10, 'Deudas', NULL, 'EXPENSE', NULL, 10);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (11, 'Gastos Bancarios', NULL, 'EXPENSE', NULL, 11);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (12, 'Otros', 1, 'EXPENSE', NULL, 12);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (13, 'Otros', 2, 'INCOME', NULL, 13);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (14, '(Sin Categoría)', 3, 'INCOME', NULL, 14);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (16, 'Comer fuera', 1, 'EXPENSE', NULL, 16);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (17, 'Compras', 1, 'EXPENSE', NULL, 17);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (18, 'Arriendo', 6, 'EXPENSE', NULL, 18);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (19, 'Plan Datos Celular', 7, 'EXPENSE', NULL, 19);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (20, 'Salario', 8, 'INCOME', NULL, 20);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (21, 'Bono', 8, 'INCOME', NULL, 21);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (22, 'Moto', 9, 'INCOME', NULL, 22);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (23, 'Ropa', 6, 'EXPENSE', NULL, 23);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (24, 'Suscripciones', 7, 'EXPENSE', NULL, 24);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (25, 'Cuotas De Manejo', 11, 'EXPENSE', NULL, 25);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (26, 'Intereses', 11, 'EXPENSE', NULL, 26);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (27, 'Comida', 6, 'EXPENSE', NULL, 27);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (28, 'Transporte', 1, 'EXPENSE', NULL, 28);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (29, 'Beneficios Bancarios', 2, 'INCOME', NULL, 29);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (30, 'Costos Bancarios', 11, 'EXPENSE', NULL, 30);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (31, 'Ayuda San Juan', 1, 'EXPENSE', NULL, 31);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (32, 'Nuevas Partes pc', 7, 'EXPENSE', NULL, 32);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (33, 'Compras Hogar', NULL, 'EXPENSE', NULL, 33);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (34, 'Accesorios', 7, 'EXPENSE', NULL, 34);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (35, 'Educación', 7, 'EXPENSE', NULL, 35);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (36, 'Ropa', 7, 'EXPENSE', NULL, 36);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (37, 'Internet', 6, 'EXPENSE', NULL, 37);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (38, 'Aseo Personal', 6, 'EXPENSE', NULL, 38);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (39, 'Seguros', 11, 'EXPENSE', NULL, 39);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (40, 'Snack', 1, 'EXPENSE', NULL, 40);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (41, 'Dinero Perdido', 1, 'EXPENSE', NULL, 41);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (42, 'Costos Médicos', 1, 'EXPENSE', NULL, 42);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (43, 'Pago Jenny', 6, 'EXPENSE', NULL, 43);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (44, 'Donaciones', 1, 'EXPENSE', NULL, 44);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (45, 'Regalos', 1, 'EXPENSE', NULL, 45);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (46, 'Viajes', 1, 'EXPENSE', NULL, 46);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (47, 'Auto ', 1, 'EXPENSE', NULL, 47);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (48, 'Compras Comida ', NULL, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (49, 'Frutas ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (50, 'Snack Alacena ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (51, 'Verduras ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (52, 'Ingredientes para Cocinar ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (53, 'Pasta ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (54, 'Leche ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (55, 'Cama', 33, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (56, 'Toallas ', 33, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (57, 'Aseo Hogar ', 33, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (58, 'Higiene personal ', 33, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (59, 'Carne de res ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (60, 'Pescado ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (61, 'Carne de cerdo ', 48, 'EXPENSE', NULL, 0);
INSERT INTO categories (id, name, parent_id, category_type, icon, sort_order) VALUES (62, 'Pollo ', 48, 'EXPENSE', NULL, 0);
