INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9001, 12, '438000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9002, 35, '189900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9003, 47, '185000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9004, 16, '125000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9005, 47, '13600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9006, 47, '287468.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9007, 12, '400000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9008, 18, '221890.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9009, 16, '70750.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9010, 47, '13600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9011, 47, '360000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9012, 24, '46900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9013, 42, '46900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9014, 12, '800000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9015, 24, '116788.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9016, 16, '7900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9017, 12, '71921.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9018, 16, '18300.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9019, 28, '29494.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9020, 19, '49900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9021, 16, '12100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9022, 24, '41900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9023, 45, '454900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9024, 28, '34192.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9025, 16, '41900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9026, 28, '35393.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9027, 24, '36900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9028, 23, '409400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9029, 24, '49900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9030, 16, '463000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9031, 45, '100838.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9032, 47, '312297.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9033, 47, '16100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9034, 16, '258617.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9035, 45, '1406270.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9036, 12, '130000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9037, 30, '125400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9038, 16, '34600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9039, 47, '12700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9040, 12, '300000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9041, 12, '35000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9042, 18, '151000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9043, 18, '307226.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9044, 35, '609700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9045, 24, '45999.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9046, 12, '98160.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9047, 42, '133050.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9048, 12, '10680.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9049, 12, '150310.10', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9050, 12, '509.23', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9051, 12, '20000000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9052, 30, '80000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9053, 12, '808483.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9054, 12, '6694889.50', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9055, 12, '6000000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9056, 12, '3939.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9057, 13, '20300453.21', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9058, 16, '10000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9059, 16, '44695.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9060, 27, '85250.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9061, 27, '156395.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9062, 24, '19971.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9063, 12, '240000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9064, 18, '155210.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9065, 31, '500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9066, 12, '20000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9067, 42, '41800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9068, 47, '11050.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9069, 47, '56000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9070, 16, '53900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9071, 47, '5400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9072, 47, '309233.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9073, 20, '7060914.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9074, 35, '15500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9075, 24, '81000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9076, 16, '112209.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9077, 17, '109000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9078, 24, '109000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9079, 24, '30900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9080, 47, '10600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9081, 18, '48786.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9082, 45, '351900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9083, 45, '94900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9084, 33, '598870.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9085, 45, '265930.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9086, 47, '246583.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9087, 12, '219000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9088, 16, '11000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9089, 16, '21750.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9090, 47, '4350.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9091, 12, '400000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9092, 16, '861509.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9093, 18, '24750.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9094, 13, '161000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9095, 24, '118282.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9096, 24, '117887.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9097, 16, '80950.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9098, 12, '60000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9099, 35, '38000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9100, 45, '529900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9101, 45, '150700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9102, 46, '201400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9103, 46, '318800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9104, 46, '253610.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9105, 46, '305118.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9106, 12, '700000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9107, 42, '9500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9108, 12, '2579268.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9109, 27, '16500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9110, 46, '304379.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9111, 45, '261000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9112, 45, '585400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9113, 45, '379820.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9114, 47, '11250.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9115, 12, '2579268.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9116, 18, '107070.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9117, 27, '299199.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9118, 12, '5099055.89', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9119, 13, '2500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9120, 30, '118100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9121, 27, '53370.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9122, 24, '120790.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9123, 42, '52000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9124, 16, '211000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9125, 19, '39900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9126, 46, '137500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9127, 46, '290425.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9128, 46, '265600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9129, 19, '49900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9130, 46, '218200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9131, 24, '7581.54', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9132, 27, '144210.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9133, 12, '694405.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9134, 42, '80000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9135, 24, '45999.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9136, 12, '168732.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9137, 16, '12000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9138, 24, '24000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9139, 12, '169255.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9140, 42, '139600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9141, 12, '73604.18', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9142, 12, '19900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9143, 13, '823421.57', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9144, 13, '597764.11', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9145, 12, '4500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9146, 30, '18000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9147, 12, '5882890.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9148, 13, '201167.50', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9149, 12, '130729.50', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9150, 12, '55350.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9151, 12, '55350.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9152, 12, '98453.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9153, 20, '5000000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9154, 47, '13561.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9155, 47, '316034.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9156, 12, '300000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9157, 31, '200000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9158, 24, '19361.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9159, 33, '3474700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9160, 27, '146220.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9161, 12, '980000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9162, 12, '21900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9163, 24, '129000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9164, 12, '189000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9165, 17, '43000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9166, 12, '91395.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9167, 12, '24.55', 'USD', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9168, 12, '80000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9169, 12, '21.49', 'USD', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9170, 18, '155210.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9171, 27, '390000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9172, 17, '87800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9173, 46, '64400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9174, 46, '285538.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9175, 24, '15500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9176, 12, '52200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9177, 24, '81000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9178, 12, '180000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9179, 24, '109000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9180, 24, '30900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9181, 18, '46346.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9182, 47, '246583.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9183, 33, '98700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9184, 16, '196100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9185, 13, '7796790.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9186, 18, '161358.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9187, 16, '118600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9188, 35, '463230.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9189, 24, '37500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9190, 16, '176700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9191, 12, '2600.03', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9192, 24, '115409.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9193, 12, '30306.05', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9194, 12, '5830460.96', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9196, 12, '187000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9197, 12, '7410.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9198, 12, '137660.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9199, 12, '450000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9200, 12, '450000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9201, 12, '300000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9202, 12, '800000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9203, 12, '350000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9204, 12, '350000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9205, 12, '700000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9206, 0, '2579268.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9207, 38, '259801.00', 'COP', 'Cascade Platinum ', '2', '129900.5', 'box');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9207, 1, '20350.00', 'COP', 'Domicilio Pricesmart', '1', '20350', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9207, 1, '1120.60', 'COP', '4x100', '1', '1120.6', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9208, 0, '500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9209, 18, '7410.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9210, 18, '107040.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9211, 18, '137660.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9212, 40, '3000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9213, 16, '95000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9214, 47, '360000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9215, 19, '49900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9216, 47, '335679.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9217, 0, '36002.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9218, 0, '2000000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9219, 16, '31900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9220, 47, '38000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9221, 47, '14100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9222, 16, '19500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9223, 16, '18500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9225, 47, '5600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9226, 0, '500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9227, 0, '900000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9229, 24, '37500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9230, 29, '32670.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9231, 29, '50000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9234, 24, '7500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9235, 24, '7000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9236, 1, '43900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9237, 47, '3820.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9238, 24, '118830.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9239, 24, '41900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9240, 2, '94376.57', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9241, 16, '60900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9242, 47, '353600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9244, 47, '288566.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9245, 47, '7000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9246, 47, '502000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9247, 42, '60000.00', 'COP', 'Valsartan', '3', '20000', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9247, 38, '29500.00', 'COP', 'Bellaface', '1', '29500', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9247, 12, '13500.00', 'COP', 'Cobros Rappi ', '1', '13500', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9248, 16, '262769.00', 'COP', 'Cena', '1', '262769', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9248, 45, '70000.00', 'COP', 'Cadena', '1', '70000', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9248, 45, '284650.00', 'COP', 'Ropa', '1', '284650', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9248, 45, '649800.00', 'COP', 'Zapatos ', '1', '649800', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9249, 38, '38000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9250, 47, '17500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9251, 45, '247984.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9252, 24, '74518.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9253, 13, '50.00', 'USD', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9254, 2, '51.95', 'USD', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9255, 24, '186297.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9256, 5, '267660.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9257, 24, '15740.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9258, 24, '677093.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9259, 40, '25800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9260, 24, '19721.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9261, 16, '72600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9262, 27, '743243.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9263, 33, '3612900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9264, 40, '21400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9265, 47, '246583.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9266, 24, '46711.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9267, 18, '47423.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9269, 45, '14950.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9270, 40, '21000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9271, 47, '14100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9272, 24, '24900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9273, 18, '161358.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9274, 35, '183448.21', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9275, 16, '56200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9276, 40, '12000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9277, 27, '490545.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9278, 13, '1206.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9279, 21, '22891146.37', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9280, 12, '610872.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9281, 31, '500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9282, 0, '103379683.11', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9285, 39, '139756.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9286, 1, '16960.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9287, 20, '5000000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9288, 20, '2500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9290, 0, '770000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9292, 0, '270000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9293, 13, '64448.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9294, 20, '1000506.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9295, 47, '360000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9297, 20, '13074065.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9298, 21, '386094.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9299, 27, '824000', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9299, 4, '3296.00', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9300, 0, '2579268.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9301, 20, '5000000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9302, 1, '37618970.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9303, 18, '161358.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9304, 1, '240000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9305, 18, '155210', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9305, 14, '620.84', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9306, 18, '94670', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9306, 14, '378.68', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9307, 0, '27150.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9308, 19, '39900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9309, 45, '2099990.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9310, 40, '17900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9311, 33, '1357030.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9312, 19, '53900', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9312, 14, '215.60', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9313, 35, '225933.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9314, 24, '41900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9315, 40, '24500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9315, 14, '98.00', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9316, 47, '4750.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9317, 47, '268547.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9318, 0, '470000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9319, 42, '159800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9320, 33, '18418.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9321, 45, '45000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9322, 0, '1300000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9325, 24, '45999.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9326, 0, '300000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9327, 40, '35200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9328, 40, '43200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9329, 40, '23000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9330, 12, '180000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9331, 42, '279393.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9332, 47, '119000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9333, 28, '14267.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9334, 1, '58720.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9335, 28, '14806.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9336, 47, '6050.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9337, 42, '46450.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9338, 0, '230000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9339, 13, '10335.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9340, 40, '35400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9341, 40, '13500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9342, 1, '734458.75', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9343, 1, '4064000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9344, 13, '1180000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9345, 13, '50000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9346, 0, '48000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9347, 13, '2000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9348, 0, '500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9349, 13, '28000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9350, 2, '48000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9351, 13, '1800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9352, 13, '600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9353, 2, '5100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9354, 2, '10900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9355, 2, '9400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9356, 2, '20200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9357, 0, '8617866.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9358, 0, '4682134.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9359, 0, '13380000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9360, 24, '19766.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9361, 24, '50750.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9362, 44, '50000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9363, 13, '16725.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9364, 16, '322315.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9365, 16, '97100.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9366, 40, '5800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9367, 16, '85700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 27, '39968.03', 'COP', 'lomo de cerdo ', '1.6', '24980.02', 'kg');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 40, '24560.00', 'COP', 'bolsa manzanas ', '2', '12280', 'bolsa ');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 27, '12069.40', 'COP', 'hígado ', '0.81', '14900.49', 'kg');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 27, '3600.00', 'COP', 'Cebolla Blanca Malla ', '1', '3600', 'malla ');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 27, '2246.90', 'COP', 'Cebolla Roja ', '0.35', '6419.72', 'kg');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 40, '35000.00', 'COP', 'Yogurt Botella Litro ', '1', '35000', 'botella ');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 40, '8690.00', 'COP', 'Golpe Ranchero ', '1', '8690', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 40, '17060.00', 'COP', 'Chocolate Barra ', '1', '17060.00', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 40, '46585.00', 'COP', 'Vino ', '1', '46585.00', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9368, 27, '141.67', 'COP', '????', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9370, 44, '50000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9371, 44, '100000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9372, 40, '58000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9373, 0, '25000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9374, 0, '780000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9375, 0, '350000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9376, 0, '350000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9377, 0, '780000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9378, 0, '620000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9379, 0, '24760.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9380, 0, '780000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9381, 0, '147410.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9382, 0, '1026000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9383, 24, '752753.88', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9385, 24, '15500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9387, 40, '10800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9388, 42, '36177.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9389, 13, '8062.49', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9391, 0, '150000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9392, 44, '50000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9393, 27, '15600.00', 'COP', 'Huevos', '30', '520', 'unir');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9393, 27, '6250.00', 'COP', 'Snack ', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9394, 0, '200000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9395, 47, '233443.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9396, 0, '200000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9397, 47, '1424734.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9398, 16, '43600.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9399, 33, '20000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9400, 45, '34900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9401, 18, '196000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9403, 45, '35000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9404, 45, '100000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9406, 45, '3529769.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9407, 44, '70000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9408, 24, '24900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9409, 42, '19710.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9410, 20, '13582228.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9411, 47, '294238.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9412, 47, '7150.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9412, 14, '28.60', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9413, 45, '60000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9413, 14, '240.00', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9415, 42, '9160.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9415, 14, '36.64', 'COP', 'GMF (4x1000)', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9416, 13, '2174800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9421, 16, '266200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9422, 16, '97787.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9423, 16, '783935.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9424, 38, '156000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9425, 40, '13500.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9426, 20, '938000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9427, 16, '61200.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9429, 55, '205800.00', 'COP', 'Cobija ', '1', '205800', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9429, 55, '169840.00', 'COP', 'Sábanas ', '1', '169840', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9429, 27, '25542.00', 'COP', 'Cerveza Estella ', '1800', '14.19', 'ml');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9429, 47, '29906.25', 'COP', 'Refrigerante ', '4785', '6.25', 'ml');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9429, 57, '45800.00', 'COP', 'Glade aparato ', '2', '22900', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '18860.40', 'COP', 'Durazno ', '1860', '10.14', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '9937.00', 'COP', 'manzana paquete ', '950', '10.46', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '21700.00', 'COP', 'arándano ', '500', '43.4', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '12450.00', 'COP', 'Fresa', '500', '24.9', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '11204.80', 'COP', 'Naranja ', '1880', '5.96', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '5596.90', 'COP', 'Mango ', '970', '5.77', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 52, '6400.00', 'COP', 'limón', '1000', '6.4', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 51, '19800.00', 'COP', 'champiñones ', '500', '39.6', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 51, '3800.00', 'COP', 'Cebolla Blanca ', '1000', '3.8', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 51, '13800.00', 'COP', 'tomate ', '2000', '6.9', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 54, '21912.00', 'COP', 'leche ', '6600', '3.32', 'ml');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 50, '51800.00', 'COP', 'yogurt griego ', '2000', '25.90', 'ml');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 40, '7562.50', 'COP', 'Electrolit', '625', '12.10', 'ml');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 50, '18558.72', 'COP', 'Tosh Miel', '648', '28.64', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 50, '26157.60', 'COP', 'Tosh Wafer ', '504', '51.90', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 50, '19121.76', 'COP', 'Tosh Cremadas ', '441', '43.36', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 50, '7501.20', 'COP', 'Tostadas', '280', '26.79', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 52, '34900.00', 'COP', 'Ghee Ajo ', '400', '87.25', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 52, '28900.00', 'COP', 'Ghee', '400', '72.25', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 53, '15936.00', 'COP', 'Espagueti ', '3200', '4.98', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 58, '36900.00', 'COP', 'Toallas higiénicas nocturnas ', '30', '1230', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 58, '21674.80', 'COP', 'Toallas Higiénicas ', '70', '309.64', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 58, '159792.00', 'COP', 'Cuchillas de Afeitar ', '16', '9987', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 58, '19900.00', 'COP', 'Enjuague bucal ', '1000', '19.90', 'ml');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '13900.05', 'COP', 'Papel Cocina ', '45', '308.89', 'm');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '5900.00', 'COP', 'Limpia vidrios palo', '1', '5900', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '5400.00', 'COP', 'Limpiador de baño en polvo ', '1000', '5.4', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '33800.00', 'COP', 'Toalla de manos ', '2', '16900', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '4900.00', 'COP', 'Chupa Baño ', '1', '4900', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '28814.94', 'COP', 'Glade Eléctrico ', '63', '457.38', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 55, '99000.00', 'COP', 'protector colchón ', '1', '99000', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 57, '4900.00', 'COP', 'recogedor ', '1', '4900', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 33, '7900.00', 'COP', 'encendedor ', '1', '7900', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9430, 49, '1319.33', 'COP', 'ajuste al peso ', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9431, 40, '69800.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9432, 16, '55400.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9433, 59, '75195.00', 'COP', 'Res', '1500', '50.13', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9433, 61, '63285.00', 'COP', 'Carne de cerdo ', '1500', '42.19', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9433, 62, '76680.00', 'COP', 'Pollo', '2000', '38.34', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9433, 60, '57538.00', 'COP', 'Tilapia ', '1300', '44.26', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9433, 0, '5310.00', 'COP', 'verduras mix', '500', '10.62', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9433, 1, '5500.00', 'COP', 'envío ', '1', '5500', 'u');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9434, 13, '0.07', 'EUR', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9435, 60, '139980.00', 'COP', 'atún ', '2000', '69.99', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9435, 60, '96592.50', 'COP', 'salmón ', '1325', '72.90', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9435, 59, '154580.00', 'COP', 'Lomo fino ', '2000', '77.29', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9435, 59, '12100.00', 'COP', 'mondongo ', '500', '24.2', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9435, 59, '12100.00', 'COP', 'hígado ', '500', '24.2', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9435, 59, '13310.00', 'COP', 'bofe ', '1000', '13.31', 'gr');
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9436, 45, '2749966.00', 'COP', 'colinas ', '1', '2749966', NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9436, 45, '489034.00', 'COP', 'Apreciación de la doña ', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9436, 12, '11000.00', 'COP', 'envío ', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9437, 18, '47672.65', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9438, 45, '78000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9439, 12, '121544.81', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9440, 45, '477300.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9441, 12, '514630.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9442, 47, '100000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9443, 24, '41900.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9444, 24, '46711.98', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9445, 1, '230000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9446, 57, '249700.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9447, 13, '291359.13', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9448, 18, '188740.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9449, 47, '77300.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9450, 24, '73516.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9451, 0, '500000.00', 'COP', '', NULL, NULL, NULL);
INSERT INTO movement_entries (movement_id, category_id, amount, currency_code, memo, quantity, unit_price, unit_label) VALUES (9452, 18, '155020.00', 'COP', '', NULL, NULL, NULL);
